[package]
name = "backup"
version = "1.0.0"
edition = "2024"

[dependencies]
rayon = "1"
ring = "0.17"
walkdir = "2"
indicatif = "0.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
globset = "0.4"
